OnlineExaminationSystem_Mvc/Controllers/OrganizationController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL;
using Models;

namespace OnlineExaminationSystem_Mvc.Controllers
{
    public class OrganizationController : Controller
    {
        OrganizationManager organizationManager=new OrganizationManager();
        //
        // GET: /Organization/
        public ActionResult OrganizationEntry()
        {
            return View();
        }
        [HttpPost]
        public ActionResult OrganizationEntry(Organization organization)
        {
            HttpPostedFileBase file = Request.Files["Image"];
            organization.Logo = ConvertToBytes(file); 
            bool isSaved = organizationManager.AddOrganization(organization);
            return View("OrganizationView",organization);
        }


        public byte[] ConvertToBytes(HttpPostedFileBase image)
        {

            byte[] imageBytes = null;

            BinaryReader reader = new BinaryReader(image.InputStream);

            imageBytes = reader.ReadBytes((int)image.ContentLength);

            return imageBytes;

        }

        public ActionResult RetrieveImage(int id)
        {

            byte[] cover = organizationManager.GetImageFromDataBase(id);

            if (cover != null)
            {

                return File(cover, "image/jpg");

            }

            else
            {

                return null;

            }

        }
        public ActionResult OrganizationSearch()
        {
            return View();
        }

        public ActionResult OrganizationInformation()
        {
            var data = organizationManager.GetOrganization();
            return View("OrganizationInformation",data);
        }
        [HttpPost]
        public JsonResult OrganizationSearch(Organization organization)
        {
            var data = organizationManager.GetOrganizationBySearchCriteria(organization);
            return Json(data.Select(o => new { o.Name, o.Code, StudentData = o.Students.Count, TrainerData = o.Trainers.Count }), JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetOrganization()
        {
            var data = organizationManager.GetOrganization();
            return Json(data.Select(o => new { o.Name, o.Code, StudentData = o.Students.Count, TrainerData = o.Trainers.Count }), JsonRequestBehavior.AllowGet);
        }

	}
}

OnlineExaminationSystem_Mvc/Views/Organization/OrganizationEntry.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


       
           


            <div class="form-horizontal">
                <h2 class="page-header"> Organization Entry</h2>
                <hr />
                @using (Html.BeginForm("OrganizationEntry","Organization", FormMethod.Post, new { enctype ="multipart/form-data" }))

                { 
                    <div class="form-group">
                        <label for="Name" class="col-md-2 col-md-offset-1"> Name: </label>
                        <div class="col-md-8">
                            <input type="text" id="Name" name="Name" class="form-control" />
                        </div>
                    </div>
                    @*<div class="form-group">
                <label for="RegNO" class="col-md-2"> Registration No: </label>
                <div class="col-md-10">

                    @Html.TextBoxFor(c => c.RegNo, new { @id = "regNoTextBox", @class = "form-control", @readonly = "readonly" })

                </div>
            </div>*@
                    <div class="form-group">
                        <label for="Code" class="col-md-2 col-md-offset-1"> Code: </label>
                        <div class="col-md-8">
                            <input type="text" id="Code" name="Code" class="form-control" readonly="readonly" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="Address" class="col-md-2 col-md-offset-1"> Address: </label>
                        <div class="col-md-8">
                            <input type="text" id="Address" name="Address" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="ContactNo" class="col-md-2 col-md-offset-1"> Contact No: </label>
                        <div class="col-md-8">
                            <input type="text" id="ContactNo" name="ContactNo" class="form-control" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="About" class="col-md-2 col-md-offset-1"> About: </label>
                        <div class="col-md-8">
                            <textarea rows="3" id="About" name="About" class="form-control"></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="Logo" class="col-md-2 col-md-offset-1"> Logo: </label>
                        <div class="col-md-8">
                            <input type="file" id="Image" name="Image" class="form-control"  />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row col-md-offset-3">
                            <input type="submit" value="Save" id="SaveButton" class="btn btn-primary" style="margin-left: 16px" />
                        </div>
                    </div>
                }

</div>
            
       
    
@section scripts{
    @*<script src="~/Scripts/jquery-1.9.1.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>*@
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/AppData/Organization/OrganizationEntry.js"></script>
}
   
   
   

OnlineExaminationSystem_Mvc/Views/Organization/OrganizationInformation.cshtml
@model List<Models.Organization>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<form method="POST">
    

    <div class="form-horizontal align-content-center">
        <table id="OrganizationViewTable" class="table table-striped table-bordered " style="width: 100%">
            <thead>
                <tr>
                    <th class="th-">
                        SL

                    </th>
                    <th class="th-lg">
                        Name
                        <i class="fa fa-sort float-right" aria-hidden="true"></i>
                    </th>
                    <th class="th-lg">
                        Code
                        <i class="fa fa-sort float-right" aria-hidden="true"></i>
                    </th>
                    <th class="th">
                        Trainers
                        <i class="fa fa-sort float-right" aria-hidden="true"></i>
                    </th>
                    <th class="th">
                        Participants
                        <i class="fa fa-sort float-right" aria-hidden="true"></i>
                    </th>
                    <th class="th">
                        Action

                    </th>

                </tr>
            </thead>
            <tbody id="OrganizationViewTableContent">
            @{ int i = 1;}
            @foreach (var organization in Model)
            {
                <tr>
                    <td> @i @{ i++;}</td>
                    <td>@organization.Name</td>
                    <td> @organization.Code</td>
                    <td> @organization.Trainers.Count</td>
                    <td> @organization.Students.Count</td>
                    <td> <a href="#">Edit</a>|<a href="#">Delete</a></td>
                </tr>
            }

            </tbody>
        </table>

    </div>





  
</form>
@section scripts{
    @*<script src="~/Scripts/jquery-1.9.1.min.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>*@
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/AppData/Organization/OrganizationEntry.js"></script>

}

OnlineExaminationSystem_Mvc/Views/Organization/OrganizationSearch.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


    @section Content
    {
        @*<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">*@
@*<link href="~/Content/MDB-Free_4.5.10/css/mdb.min.css" rel="stylesheet" />
    <link href="~/Content/MDB-Free_4.5.10/css/style.css" rel="stylesheet" />
    <link href="~/Content/MDB-Free_4.5.10/css/addons/datatables.min.css" rel="stylesheet" />*@



    }


<form method="POST">
            <h2> Organization Search Criteria</h2>
            <hr />



            <div class="form-horizontal">




                <div class="form-group">
                    <label for="Name" class="col-md-2"> Name: </label>
                    <div class="col-md-4">
                        <input type="text" id="Name" name="Name" class=" form-control form-group" />
                    </div>


                    <label for="Code" class="col-md-2"> Code: </label>
                    <div class="col-md-4">
                        <input type="text" id="Code" name="Code" class="form-control form-group" />

                    </div>


                    <label for="Address" class="col-md-2"> Address: </label>
                    <div class="col-md-4">
                        <input type="text" id="Address" name="Address" class="form-control form-group" />
                    </div>


                    <label for="ContactNo" class="col-md-2"> Conatact No: </label>
                    <div class="col-md-4">
                        <input type="text" id="ContactNo" name="ContactNo" class="form-control form-group" />
                    </div>

                    <div class="col-md-2 col-md-offset-2">
                        <input type="button" id="SeachOrganizationButton" name="SeachOrganizationButton" value="Search" class="form-control form-group btn btn-info" />
                    </div>
                </div>
                
            </div>
        </form>


        <table id="OrganizationSearchTable" class="table table-striped table-bordered " style="width: 100%">
            <thead>
                <tr>
                    <th class="th-">
                        SL

                    </th>
                    <th class="th-lg">
                        Name
                        <i class="fa fa-sort float-right" aria-hidden="true"></i>
                    </th>
                    <th class="th-lg">
                        Code
                        <i class="fa fa-sort float-right" aria-hidden="true"></i>
                    </th>
                    <th class="th">
                        Trainers
                        <i class="fa fa-sort float-right" aria-hidden="true"></i>
                    </th>
                    <th class="th">
                        Students
                        <i class="fa fa-sort float-right" aria-hidden="true"></i>
                    </th>
                    <th class="th">
                        Action
                        <i class="fa fa-sort float-right" aria-hidden="true"></i>
                    </th>

                </tr>
            </thead>
            <tbody id="OrganizationSearchTableContent"></tbody>
        </table>

    @section scripts{
        @*<script type="text/javascript" src="~/Content/MDB-Free_4.5.10/js/jquery-3.3.1.min.js"></script>
<script type="text/javascript" src="~/Content/MDB-Free_4.5.10/js/bootstrap.min.js"></script>*@
@*<script type="text/javascript" src="~/Content/MDB-Free_4.5.10/js/popper.min.js"></script>

    <script type="text/javascript" src="~/Content/MDB-Free_4.5.10/js/mdb.min.js" ></script>
    <script type="text/javascript" src="~/Content/MDB-Free_4.5.10/js/addons/datatables.min.js"></script>*@

<script src="~/Scripts/AppData/Organization/OrganizationSearch.js"></script>

    }
  

OnlineExaminationSystem_Mvc/Views/Organization/OrganizationView.cshtml
@model Models.Organization

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


        <form method="POST">
            <div class="row">
                <div class="form-group">
                    <div class="col-md-3">
                        <img src="~/Organization/RetrieveImage/@Model.Id" alt="" height=200 width=200/>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="form-group">
                                <h1 class="page-header col-md-8"> @Model.Name</h1>
                                <div class="col-md-">
                                    <div class="form-group" style="margin-top: 30px">
                                        <a href="@Url.Action("OrganizationSearch", "Organization")" class="elements"> <span class="glyphicon glyphicon-chevron-left">Search</span></a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <h3> @Model.About</h3>
                            </div>
                        </div>
                        
                     </div>
                        
                   
                </div>
            </div>
            

            <div class="form-horizontal align-content-center">
                <table id="OrganizationViewTable" class="table table-striped table-bordered " style="width: 100%">
                    <thead>
                        <tr>
                            <th class="th-">
                                SL

                            </th>
                            <th class="th-lg">
                                Name
                                <i class="fa fa-sort float-right" aria-hidden="true"></i>
                            </th>
                            <th class="th-lg">
                               Code
                                <i class="fa fa-sort float-right" aria-hidden="true"></i>
                            </th>
                            <th class="th">
                                Trainers
                                <i class="fa fa-sort float-right" aria-hidden="true"></i>
                            </th>
                            <th class="th">
                                Participants
                                <i class="fa fa-sort float-right" aria-hidden="true"></i>
                            </th>
                            <th class="th">
                                Action
                                
                            </th>

                        </tr>
                    </thead>
                    <tbody id="OrganizationViewTableContent"></tbody>
                </table>

            </div>





            <div class="card-footer">

               

                <div class="row">
                    <h4> @Model.Address</h4>
                </div>
                <div class="row">
                    <h4> @Model.ContactNo</h4>
                </div>

            </div>
        </form>
@section scripts{
    @*<script src="~/Scripts/jquery-1.9.1.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>*@
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/AppData/Organization/OrganizationEntry.js"></script>

}
    