OnlineExaminationSystem_Mvc/ViewModels/Course/CourseEntryVm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Models;

namespace OnlineExaminationSystem_Mvc.ViewModels.Course
{
    public class CourseEntryVm
    {
        public int Id { get; set; }
        public int OrganizationId { get; set; }
        public virtual ICollection<Organization> Organizations { get; set; }
        [Required]
        [MaxLength(50)]
        public string CourseName { get; set; }
        [Required]
        [MaxLength(50)]
        public string CourseCode { get; set; }
        public double Duration { get; set; }
        public double Credit { get; set; }
        public string Outline { get; set; }
        public int TagsId { get; set; }
        public virtual ICollection<Tags> Tags { get; set; }
        public int TrainerId { get; set; }
        public virtual ICollection<Models.Trainer> Trainers { get; set; }
        public bool TrainerType { get; set; }
        public virtual ICollection<Models.Student> Students { get; set; }
        public virtual ICollection<Exams> Examses { get; set; }

        public List<SelectListItem> SelectListItems { get; set; }
        public List<SelectListItem> SelectCourseSelectListItemsListItems { get; set; }
        public List<SelectListItem> SelectTagListItems { get; set; }
        public List<SelectListItem> SelectTrainerListItem { get; set; }
        public List<SelectListItem> ExamTypeSelectListItems { get; set; }
    }
}

OnlineExaminationSystem_Mvc/ViewModels/Course/CourseUpdateVm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Models;

namespace OnlineExaminationSystem_Mvc.ViewModels.Course
{
    public class CourseUpdateVm
    {
        public int Id { get; set; }
        public int OrganizationId { get; set; }
        public virtual ICollection<Organization> Organizations { get; set; }
        [Required]
        [MaxLength(50)]
        public string CourseName { get; set; }
        [Required]
        [MaxLength(50)]
        public string CourseCode { get; set; }
        public double Duration { get; set; }
        public double Credit { get; set; }
        public string Outline { get; set; }
        public int TagsId { get; set; }
        public virtual ICollection<Tags> Tags { get; set; }
        public virtual ICollection<Models.Trainer> Trainers { get; set; }
        public bool TrainerType { get; set; }
        public virtual ICollection<Models.Student> Students { get; set; }
        public virtual ICollection<Exams> Examses { get; set; }

        public List<SelectListItem> SelectListItems { get; set; }
        public List<SelectListItem> SelectTagListItems { get; set; }
    }
}

OnlineExaminationSystem_Mvc/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using AutoMapper.Internal;
using BLL;
using DatabaseContext;
using Models;
using OnlineExaminationSystem_Mvc.ViewModels.Course;
using OnlineExaminationSystem_Mvc.ViewModels.Exam;

namespace OnlineExaminationSystem_Mvc.Controllers
{
    public class CourseController : Controller
    {
        CourseManager manager = new CourseManager();
        
        //
        // GET: /Course/
        public ActionResult Entry()
        {

            CourseEntryVm courseEntryVm = new CourseEntryVm();


            courseEntryVm.SelectListItems = GetSelectListItem();
            courseEntryVm.SelectTagListItems = GetTextListItem();
            return View(courseEntryVm);

        }


        [HttpPost]
        public ActionResult Entry(CourseEntryVm courseVm)
        {



            // var tuple = new Tuple<Organization, Tags>(new Organization(), new Tags());

            //tuple.Item1.SelectListItems = GetSelectListItem();
            //tuple.Item2.SelectTagListItems = GetTextListItem();

            var course = Mapper.Map<Course>(courseVm);
            var organization = manager.GetOrganizationsById(courseVm.OrganizationId);
            var Tags = manager.GetTagById(courseVm.TagsId);
            course.Organizations = organization.ToList();
            course.Tags = Tags.ToList();
           
            bool isSaved = manager.addCourse(course);
            if (isSaved)
            {
                courseVm.SelectTrainerListItem = GetTrainerListItem();
                courseVm.SelectCourseSelectListItemsListItems = GetCourseListItem();
                courseVm.ExamTypeSelectListItems = GetExamTypeListItem();
                courseVm.SelectListItems = GetSelectListItem();
                courseVm.SelectTagListItems = GetTextListItem();
                courseVm.Id = course.Id;
                courseVm.Organizations = course.Organizations;
                courseVm.Tags = course.Tags;
                return View("AddCourse", courseVm);
            }
            return View();
        }
        public ActionResult AddCourse()
        {
            //  courseVm.SelectTrainerListItem = GetTrainerListItem();
            CourseEntryVm courseEntryVm = new CourseEntryVm();
            courseEntryVm.SelectCourseSelectListItemsListItems = GetCourseListItem();
            courseEntryVm.SelectListItems = GetSelectListItem();
            courseEntryVm.SelectTagListItems = GetTextListItem();
            courseEntryVm.SelectTrainerListItem = GetTrainerListItem();
            courseEntryVm.ExamTypeSelectListItems = GetExamTypeListItem();
            return View(courseEntryVm);
        }
        [HttpPost]
        public ActionResult AddCourse(CourseEntryVm courseVm)
        {
            //  courseVm.SelectTrainerListItem = GetTrainerListItem();
            courseVm.SelectListItems = GetSelectListItem();
            courseVm.SelectCourseSelectListItemsListItems = GetCourseListItem();
            courseVm.SelectTagListItems = GetTextListItem();
            courseVm.SelectTrainerListItem = GetTrainerListItem();
            courseVm.ExamTypeSelectListItems = GetExamTypeListItem();
            var course = Mapper.Map<Course>(courseVm);
            var organization = manager.GetOrganizationsById(courseVm.OrganizationId);
            var Tags = manager.GetTagById(courseVm.TagsId);
            course.Organizations = organization.ToList();
            course.Tags = Tags.ToList();
            var courseVmM = Mapper.Map<CourseEntryVm>(course);
            courseVmM.SelectTrainerListItem = GetTrainerListItem();
            return View(courseVmM);
        }
        public List<SelectListItem> GetExamTypeListItem()
        {

            List<SelectListItem> examTypeStItems = new List<SelectListItem>()
            {
                new SelectListItem(){
                              Text = "Class Test",
                              Value = "1"
                },
                new SelectListItem(){
                              Text = "Lab Test",
                              Value = "2"
                }
    
            };
            return examTypeStItems;
        }

        public ActionResult TrainerAdded()
        {
            return View();
        }

        [HttpPost]
        public ActionResult TrainerAdded(CourseEntryVm courseEntryVm)
        {
            bool isSaved = false;
            var course = Mapper.Map<Course>(courseEntryVm);
            course = manager.GetLastAddedCourse()[0];
            foreach (var trainer in courseEntryVm.Trainers)
            {

                var trainerAdd = manager.GetTrainerByName(trainer);
                if (courseEntryVm.TrainerType)
                {
                    course.LeadTrainer = trainerAdd[0].Id;
                }
                course.Trainers = trainerAdd;
                isSaved = manager.UpdateCourseInfo(course);
                if (!isSaved)
                {
                    return View("AddCourse");
                }
            }


            return View();

        }

        public ActionResult SearchCourse()
        {
            CourseEntryVm courseEntryVm = new CourseEntryVm();


            courseEntryVm.SelectListItems = GetSelectListItem();
            courseEntryVm.SelectTagListItems = GetTextListItem();
            return View(courseEntryVm);
        }


        public ActionResult UpdatedCourseView(CourseEntryVm courseVm)
        {

            courseVm.SelectListItems = GetSelectListItem();
            courseVm.SelectTagListItems = GetTextListItem();

            return View(courseVm);
        }
        [HttpPost]
        public ActionResult UpdatedCourseView(CourseUpdateVm courseUpdateVm)
        {

            var course = Mapper.Map<Course>(courseUpdateVm);
            var organization = manager.GetOrganizationsById(courseUpdateVm.OrganizationId);
            var Tags = manager.GetTagById(courseUpdateVm.TagsId);
            course.Organizations = organization.ToList();
            course.Tags = Tags.ToList();
            bool isSave = manager.UpdateCourseInfo(course);
            var courseEntryVm = Mapper.Map<CourseEntryVm>(course);
            courseEntryVm.SelectTrainerListItem = GetTrainerListItem();
            courseEntryVm.ExamTypeSelectListItems = GetExamTypeListItem();
            courseEntryVm.SelectCourseSelectListItemsListItems = GetCourseListItem();
            courseEntryVm.SelectListItems = GetSelectListItem();
            if (isSave)
            {    
                return View("AddCourse", courseEntryVm);
            }

            return View(courseEntryVm);

        }




        //public PartialViewResult AddCourse(Course course)
        //{
        //    bool isSaved=manager.addCourse(course);
        //    if (isSaved)
        //    {
        //        return PartialView("~\\VIews\\Shared\\AddCourse\\Add.cshtml");
        //    }
        //    return PartialView("~\\VIews\\Shared\\AddCourse\\Add.cshtml");
        //}


        public List<SelectListItem> GetTextListItem()
        {
            var TagList = manager.GetTag();
            List<SelectListItem> TagSTItems = new List<SelectListItem>();
            foreach (var Tags in TagList)
            {
                var osli = new SelectListItem();
                osli.Text = Tags.TagList;
                osli.Value = Tags.Id.ToString();
                TagSTItems.Add(osli);
            }
            return TagSTItems;
        }
        public List<SelectListItem> GetTrainerListItem()
        {
            var TrainerList = manager.GetTrainer();
            List<SelectListItem> TrainerSTItems = new List<SelectListItem>();
            foreach (var trainers in TrainerList)
            {
                var osli = new SelectListItem();
                osli.Text = trainers.Name;
                osli.Value = trainers.Id.ToString();
                TrainerSTItems.Add(osli);
            }
            return TrainerSTItems;
        }
        public List<SelectListItem> GetCourseListItem()
        {
            var courseList = manager.GetCourse();
            List<SelectListItem> CourseSTItems = new List<SelectListItem>();
            foreach (var courses in courseList)
            {
                var osli = new SelectListItem();
                osli.Text = courses.CourseName;
                osli.Value = courses.Id.ToString();
                CourseSTItems.Add(osli);
            }
            return CourseSTItems;
        }

        public List<SelectListItem> GetSelectListItem()
        {
            var organizations = manager.GetOrganization();
            List<SelectListItem> OrganizationSLItems = new List<SelectListItem>();
            foreach (var organizatio in organizations)
            {
                var osli = new SelectListItem();
                osli.Text = organizatio.Name;
                osli.Value = organizatio.Id.ToString();
                OrganizationSLItems.Add(osli);
            }
            return OrganizationSLItems;
        }




        public JsonResult SearchByCourseProperty(Course course)
        {
            var dataList = manager.GetCourseByName(course);        
            return Json(dataList.Select(c=> new {c.Id, c.CourseName,c.Duration, TrainerData = c.Trainers.Select(t=>new{t.Name}) }), JsonRequestBehavior.AllowGet);
        }


        public JsonResult CourseExamAdd(ExamEntryVm examEntryVm)
        {
            var course=manager.GetLastAddedCourse();
            examEntryVm.CourseId = course[0].Id;
            examEntryVm.Duration = TimeSpan.FromHours(Convert.ToDouble(examEntryVm.Hour)) + TimeSpan.FromMinutes(Convert.ToDouble(examEntryVm.Minute));

            var exam = Mapper.Map<Exams>(examEntryVm);
            var data=new List<Exams>();
            bool isSaved = manager.AddExam(exam);
            if (isSaved)
            {
                data=manager.GetLastAddedExam();

            }

OnlineExaminationSystem_Mvc/Views/Course/AddCourse.cshtml
@using System.Web.Mvc.Html
@using Models
@model OnlineExaminationSystem_Mvc.ViewModels.Course.CourseEntryVm
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section Content
{
    @*<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">*@
<link href="~/Content/AddCourse/TabBarCSS.css" rel="stylesheet" />
}
<form method="POST">

            <div class="form-group">
                <div class="col-md-8">
                    <h2> Course Details</h2>
                </div>
                <div class="col-md-2 form-group " style="margin-top: 30px">
                    <a href="@Url.Action("UpdatedCourseView", "Course",@Model)" class="elements"><span class="glyphicon glyphicon-chevron-left">Edit</span></a>
                </div>

                <div class="col-md-2 form-group " style="margin-top: 30px">
                    <a href="@Url.Action("SearchCourse", "Course")" class="elements"> <span class="glyphicon glyphicon-chevron-left">Search</span></a>
                </div>
            </div>
        </form>
            <div>
                <ul class="nav nav-tabs">
                    <li class="active">
                        <a href="#tab1">Basic Information</a>
                    </li>
                    <li>
                        <a href="#tab2">Assign Trainers</a>
                    </li>
                    <li>
                        <a href="#tab3">Create Exams</a>
                    </li>
                </ul>
            </div>
            <section id="tab1" class="tab-content active">
                @if (Model.CourseName == null)
                {
                    <h4> No Course Selected </h4>
                }
                else
                {
                    <div class="container">
                        <h1>Course Information</h1>
                        <br />
                        <hr />

                        <form method="POST">
                            <div class="row">
                                <div class="form-group col-md-10">
                                    <label class="form-group  col-md-2 col-md-offset-4">Organization</label>
                                    <p class=" col-md-6" style="font-size: 24px; font-weight: bold">
                                        @{
                    string Name = "";
                    foreach (var organizationName in Model.Organizations)
                    {
                        Name = organizationName.Name;
                    }
                    @Name
                                        }
                                    </p>
                                </div>
                                <div class="form-group col-md-10">
                                    <label class="form-group col-md-2 col-md-offset-4"> Course Name:</label>
                                    <p class="col-md-6" style="font-size: 20px; font-weight: bold"> @Model.CourseName</p>
                                </div>
                                <div class="form-group col-md-10">
                                    <label class="form-group  col-md-2 col-md-offset-4"> Course Code</label>
                                    <p class="col-md-6" style="font-size: 20px; font-weight: bold">@Model.CourseCode</p>
                                </div>
                                <div class="form-group col-md-10">
                                    <label class="form-group  col-md-2 col-md-offset-4">Duration</label>
                                    <p class="col-md-6" style="font-size: 20px; font-weight: bold">@Model.Duration</p>
                                </div>
                                <div class="form-group col-md-10">
                                    <label class="form-group  col-md-2 col-md-offset-4"> Credit</label>
                                    <p class="col-md-6" style="font-size: 20px; font-weight: bold"> @Model.Credit</p>
                                </div>
                            </div>




                        </form>



                    </div>
                }


            </section>
            <section id="tab2" class="tab-content hide">
                <div class="form-horizontal">
                    <div class="form-group">
                        <label for="Trainer" class="col-md-2"> Trainer: </label>
                        <div class="col-md-6" id="TrainerDropDown">

                            @Html.DropDownListFor(c => c.SelectTrainerListItem, Model.SelectTrainerListItem, "----Select---", new { @id = "Trainer", @class = "form-control" })
                            @Html.HiddenFor(c => c.TrainerId)
                        </div>
                        <div class="col-md-2"></div>
                        <div class="col-md-2 form-group ">
                            <button class="btn btn-primary" id="AddTrainerButton">Add <span class="glyphicon glyphicon-chevron-right"></span></button>
                        </div>
                    </div>
                    <div class="panel-group">
                        <div class="panel panel-success">
                            <div class="panel-heading">
                                <div class="panel-title">Added Trainer for @Model.CourseName</div>
                            </div>
                            <div class="panel-body">
                                <table class="table table-bordered table-hover table-striped table-responsive">

                                    <thead>
                                        <tr style="background-color: green; color: white; font-weight: bold">
                                            <td>Sl</td>
                                            <td>Name</td>
                                            <td>Lead Trainer?</td>
                                            <td>Action</td>
                                        </tr>
                                    </thead>

                                    <tbody id="tranierDetailsBody"></tbody>
                                </table>
                                <div class="form-group">
                                    <div class="row" style="margin-left: 18px">
                                        <input type="submit" value="Save" id="SaveTrainerButton" class="btn btn-info col-md-offset-2" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </section>
        <section id="tab3" class="tab-content hide">


            <div class="container">
                <form method="POST">
                    <h2> Exam Entry</h2>
                    <hr />



                    <div class="form-horizontal">
                        <div class="form-group">
                            <label for="OrganizationDD" class="col-md-2"> Organization: </label>
                            <div class="col-md-10">
                                @{
                                    string Organization = "";

                                    foreach (var organizationName in Model.Organizations)
                                    {
                                        Organization = organizationName.Name;

                                    }
                                }
                                @Html.DropDownListFor(c => c.SelectListItems, Model.SelectListItems, Organization, new { @id = "OrganizationDD", @class = "form-control", @disabled = true })


                            </div>
                        </div>
                        <div class="form-group">
                            <label for="CourseId" class="col-md-2"> Course: </label>
                            <div class="col-md-10">
                                @Html.DropDownListFor(c => c.SelectCourseSelectListItemsListItems, Model.SelectCourseSelectListItemsListItems, @Model.CourseName, new { @id = "CourseTB", @class = "form-control", @disabled = true })




                            </div>

                        </div>
                        <div class="form-group">
                            <label for="ExamType" class="col-md-2"> Exam Type </label>
                            <div class="col-md-10">
                                @Html.DropDownListFor(c => c.ExamTypeSelectListItems, Model.ExamTypeSelectListItems, "----Select---", new { @class = "form-control", @id = "ExamTypeDD" })

                            </div>

                        </div>

                        <div class="form-group">
                            <label for="ExamCode" class="col-md-2"> Code: </label>
                            <div class="col-md-10">
                                <input type="text" id="ExamCode" name="ExamCode" class="form-control" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="Topic" class="col-md-2"> Topic: </label>
                            <div class="col-md-10">
                                <input type="text" id="Topic" name="Topic" class="form-control" />

                            </div>
                        </div>
                        <div class="form-group">
                            <label for="FullMarks" class="col-md-2"> Full Marks: </label>
                            <div class="col-md-10">
                                <input type="text" id="FullMarks" name="FullMarks" class="form-control" />
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="Duration" class="col-md-2"> Duration: </label>
                            <div class="col-xs-2">
                                <input class="form-control" id="Hour" name="Hour" type="text">
                            </div>
                            <label class="col-sm-1" style="line-height: 2.5; width: 0%"> : </label>
                            <div class="col-xs-2 col-md-offset-0">

                                <input class="form-control" id="Minute" name="Minute" type="text">
                            </div>

                        </div>
                        <div class="form-group">

                            <div class="col-md-3" style="margin-left: 17%">
                                <input type="button" id="SaveExamButton" value="Save" class="form-control btn btn-primary" />
                            </div>
                        </div>



                        <table class="table table-bordered table-hover table-striped table-responsive" id="OptionTable">

                            <thead>
                                <tr style="background-color: blue; color: white; font-weight: bold">
                                    <td>Exam Type</td>
                                    <td>Topic</td>
                                    <td>Exam Code</td>
                                    <td>Duration</td>
                                    <td>Full Marks</td>
                                    <td>Action</td>
                                </tr>
                            </thead>

                            <tbody id="CourseExamTable"></tbody>
                        </table>


                    </div>
                </form>

            </div>
        </section>

@section scripts{
    @*<script src="~/Scripts/bootstrap.min.js"></script>


<script src="~/Scripts/jquery-1.9.1.min.js"></script>*@

<script src="~/Scripts/AppData/Course/Entry.js"></script>

}

   

OnlineExaminationSystem_Mvc/Views/Course/Entry.cshtml
@using System.Web.Mvc.Html
@using Models
@model OnlineExaminationSystem_Mvc.ViewModels.Course.CourseEntryVm
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}



    <form method="POST">
        <h2> Course Entry</h2>
        <hr/>



        <div class="form-horizontal">
            <div class="form-group">
                <label for="OrganizationId" class="col-md-2"> Organization: </label>
                <div class="col-md-10">
                    @Html.DropDownListFor(c => c.OrganizationId, Model.SelectListItems, "----Select---", new { @class = "form-control" })
                    @Html.HiddenFor(c => c.OrganizationId)
                </div>
            </div>



            <div class="form-group">
                <label for="CourseName"  class="col-md-2"> Name: </label>
                <div class="col-md-10">
                    <input type="text" id="CourseName" name="CourseName" class="form-control" />
                </div>
            </div>
            <div class="form-group">
                <label for="CourseCode" class="col-md-2"> Course Code: </label>
                <div class="col-md-10">
                    <input type="text" id="CourseCode" name="CourseCode" class="form-control" />

                </div>
            </div>
            <div class="form-group">
                <label for="Duration" class="col-md-2"> Duration: </label>
                <div class="col-md-10">
                    <input type="text" id="Duration" name="Duration" class="form-control" />
                </div>
            </div>
            <div class="form-group">
                <label for="Credit" class="col-md-2"> Credit: </label>
                <div class="col-md-10">
                    <input type="text" id="Credit" name="Credit" class="form-control" />
                </div>
            </div>
            <div class="form-group">
                <label for="Outline" class="col-md-2"> Outline: </label>
                <div class="col-md-10">
                    <input type="text" id="Outline" name="Outline" class="form-control" />
                </div>
            </div>
            <div class="form-group">
                <label for="Tag" class="col-md-2"> Tags: </label>
                <div class="col-md-10">
                    @Html.DropDownListFor(c => c.TagsId, Model.SelectTagListItems, "----Select---", new { @class = "form-control", @id = "Tags", @name = "Tags" })
                    @Html.HiddenFor(c => c.TagsId)
                  


                </div>

            </div>

            

            <div class="form-group">
                <div class="row " style="margin-left: 17px">
                    <input type="submit" value="Save" id="SaveButton" class="btn btn-primary col-md-offset-2" />
                </div>
            </div>


        </div>
    </form>



@section scripts{
    @*<script src="~/Scripts/jquery-1.9.1.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>*@
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

<script src="~/Scripts/AppData/Course/Entry.js"></script>

}

OnlineExaminationSystem_Mvc/Views/Course/TrainerAdded.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>TrainerAdded</title>
</head>
<body>
<div>
    <h1>Successfully Added Trainer</h1>
</div>
</body>
</html>