OnlineExaminationSystem_Mvc/Controllers/ExamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using BLL;
using Models;
using OnlineExaminationSystem_Mvc.ViewModels;
using OnlineExaminationSystem_Mvc.ViewModels.Exam;

namespace OnlineExaminationSystem_Mvc.Controllers
{
    public class ExamController : Controller
    {
        ExamManager examManager = new ExamManager();

        // GET: Exam
        public ActionResult Entry()
        {
            ExamEntryVm examEntryVm = new ExamEntryVm();
            examEntryVm.OrganizationSelectListItems = GetOrganizationListItem();
            examEntryVm.CourseSelectListItems = GetCourseListItem();
            examEntryVm.ExamTypeSelectListItems = GetExamTypeListItem();

            return View(examEntryVm);
        }

        [HttpPost]
        public ActionResult Entry(ExamEntryVm examEntryVm)
        {
            examEntryVm.Duration = TimeSpan.FromHours(Convert.ToDouble(examEntryVm.Hour))+TimeSpan.FromMinutes(Convert.ToDouble(examEntryVm.Minute));
            
            var exam = Mapper.Map<Exams>(examEntryVm);
            bool isSaved = examManager.AddExam(exam);
            if (isSaved)
            {
               return RedirectToAction("QuestionAnswerEntry");
            }
            return View();
        }

        public ActionResult QuestionAnswerEntry()
        {
            ExamEntryVm examEntryVm = new ExamEntryVm();
            examEntryVm.OrganizationSelectListItems = GetOrganizationListItem();
            examEntryVm.CourseSelectListItems = GetCourseListItem();
            examEntryVm.ExamTypeSelectListItems = GetExamTypeListItem();
            return View(examEntryVm);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult QuestionAnswerEntry(Question question)
        {

         
            bool isSaved = examManager.AddQuestion(question);
            if (isSaved)
            {

                return RedirectToAction("QuestionSummary", question);
            }


            return View();
        }


        public ActionResult QuestionSummary(Question question)
        {

            return View(question);
        }



        public ActionResult ExamAttend()
        {
            ExamAttendVm examAttendVm = new ExamAttendVm();
            examAttendVm.OrganizationSelectListItems = GetOrganizationListItem();
            examAttendVm.CourseSelectListItems = GetCourseListItem();
            examAttendVm.ExamTypeSelectListItems = GetExamTypeListItem();
            examAttendVm.ParticipantSelectListItems = GetParticipantsListItem();

            return View(examAttendVm);
        }

        [HttpPost]
        public ActionResult ExamAttend(ExamAttendVm examAttendVm)
        {

            var exams = Mapper.Map<Exams>(examAttendVm);
            var data = examManager.GetExamByCourseExam(exams);
            var courseName = examManager.GetCourseById(exams.CourseId);
            var examStartData = Mapper.Map<ExamAttendVm>(data);
            examStartData.Question = data.Questions;
            examStartData.CourseName = courseName.CourseName;
            examStartData.OrganizationName = examAttendVm.OrganizationName;
            examStartData.StudentId = examAttendVm.StudentId;
            return View("ExamStart", examStartData);
        }
     

        public ActionResult ExamResult()
        {
            ExamAttendVm examAttendVm = new ExamAttendVm();
            examAttendVm.OrganizationSelectListItems = GetOrganizationListItem();
            examAttendVm.CourseSelectListItems = GetCourseListItem();
            examAttendVm.ParticipantSelectListItems = GetParticipantsListItem();
            return View(examAttendVm);
        }

        [HttpPost]
        public ActionResult ExamResult(ExamAttendVm examAttendVm)
        {
            var result=new List<ResultVm>();
            var data = examManager.GetResult(examAttendVm.CourseId,examAttendVm.StudentId);
            foreach (Result results in data)
            {

                var resultVm = Mapper.Map<ResultVm>(results);
                var course=examManager.GetCourseById(examAttendVm.CourseId);
                foreach (var exams in course.Examses)
                {
                    if (exams.Id == resultVm.ExamsId)
                    {
                        resultVm.Code = exams.ExamCode;
                    }
                }
                resultVm.CourseName = course.CourseName;
                 resultVm.OrganizationName = examAttendVm.OrganizationName;
                result.Add(resultVm);
               
            }


            return View("Result", result);
        }
      



        public List<SelectListItem> GetCourseListItem()
        {
            var courseList = examManager.GetCourse();
            List<SelectListItem> courseStItems = new List<SelectListItem>();
            foreach (var courses in courseList)
            {
                var osli = new SelectListItem();
                osli.Text = courses.CourseName;
                osli.Value = courses.Id.ToString();
                courseStItems.Add(osli);
            }
            return courseStItems;
        }
        public List<SelectListItem> GetExamTypeListItem()
        {

            List<SelectListItem> examTypeStItems = new List<SelectListItem>()
            {
                new SelectListItem(){
                              Text = "Class Test",
                              Value = "1"
                },
                new SelectListItem(){
                              Text = "Lab Test",
                              Value = "2"
                }
    
            };
            return examTypeStItems;
        }

        public List<SelectListItem> GetParticipantsListItem()
        {
            var participantsList = examManager.GetParticipants();
            List<SelectListItem> participantsStItems = new List<SelectListItem>();
            foreach (var students in participantsList)
            {
                var osli = new SelectListItem();
                osli.Text = students.Name;
                osli.Value = students.Id.ToString();
                participantsStItems.Add(osli);
            }
            return participantsStItems;
        }
        public List<SelectListItem> GetOrganizationListItem()
        {
            var organizationList = examManager.GetOrganization();
            List<SelectListItem> organizationStItems = new List<SelectListItem>();
            foreach (var organization in organizationList)
            {
                var osli = new SelectListItem();
                osli.Text = organization.Name;
                osli.Value = organization.Id.ToString();
                organizationStItems.Add(osli);
            }
            return organizationStItems;
        }
        public JsonResult GetCourseByOrganizationId(int id)
        {
            var courses = new List<Course>();
            var dataList = examManager.GetOrganizationById(id);

            foreach (var organization in dataList)
            {
                courses.AddRange(organization.Courses);
            }
            return Json(courses.Select(c=> new {c.Id,c.CourseName }), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetStudentExamByCourseId(int id)
        {
            var data = examManager.GetStudentExamById(id);

            return Json(data.Examses.Select(ce=>new{ce.Id,ce.ExamCode,StudentData=data.Students.Select(cs=>new{cs.Id,cs.Name})}),JsonRequestBehavior.AllowGet);
   }

       

     
        public JsonResult GetQuestion()
        {
            var data = examManager.GetQuestionWithOption();


            return Json(data.Select(q=> new{q.Id,q.QuestionOrder,q.Marks,q.QuestionText,QuestionData=q.QuestionAnswers.Select(qa=>new{qa.IsAnswer,qa.OptionText})}), JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetOptionByQuestionId(int id)
        {
            var data = examManager.GetOption(id);


            return Json(data.Select(q => new { q.OptionText,q.OptionOder,q.IsAnswer }), JsonRequestBehavior.AllowGet);
        }
       
        public JsonResult GetExamCodeByCourseId(int id)
        {
            
            var dataList = examManager.GetExamCodeById(id);

            return Json(dataList.Select(c=> new {c.Id,c.ExamCode}), JsonRequestBehavior.AllowGet);
        }

        
        public JsonResult EvaluateAnswers(List<Question> questions,int StudentId,int CourseId)
        {
            ResultVm resultVm = new ResultVm();
            var Marks = 0;
            foreach (var question in questions)
            {
                resultVm.ExamsId = question.ExamsId;
                foreach (var questionAnswer in question.QuestionAnswers)
                {     
                var data = examManager.GetQuestionbyOrder(question);
                 //var answer = examManager.GetQuestionAnswer(data);

                    foreach (var dataAnswers in data.QuestionAnswers)
                    {
                        if (questionAnswer.OptionText == dataAnswers.OptionText && dataAnswers.IsAnswer)
                        {

                            
                            Marks = Marks + Convert.ToInt32(data.Marks);
                           
                        }
                    }
                  
                }
            }
            
            resultVm.StudentId = StudentId;
            resultVm.CourseId = CourseId;
            var result = Mapper.Map<Result>(resultVm);
            result.Students.Add(examManager.GetStudentById(StudentId));
            result.Courses.Add(examManager.GetCourseById(CourseId));
            result.ObtainedMarks = Marks;
            bool isSaved = examManager.SaveResult(result);
            return Json(JsonRequestBehavior.AllowGet);

            
        }



    }
}

OnlineExaminationSystem_Mvc/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using BLL;
using Models;
using OnlineExaminationSystem_Mvc.ViewModels.Student;

namespace OnlineExaminationSystem_Mvc.Controllers
{
    public class StudentController : Controller
    {

        StudentManager studentManager=new StudentManager();

        // GET: Student
        public ActionResult StudentEntry()
        {
            StudentEntryVm studentEntryVm=new StudentEntryVm();
            studentEntryVm.OrganizationSelectListItems = GetOrganizationListItem();
            studentEntryVm.CourseSelectListItems = GetCourseListItem();

            return View(studentEntryVm);
        }
    
    [HttpPost]
        public ActionResult StudentEntry(StudentEntryVm studentEntryVm)
        {
            HttpPostedFileBase file = Request.Files["Logo"];
            studentEntryVm.Image = ConvertToBytes(file); 
            studentEntryVm.OrganizationSelectListItems = GetOrganizationListItem();
            studentEntryVm.CourseSelectListItems = GetCourseListItem();
        var student = Mapper.Map<Student>(studentEntryVm);
        var organization = studentManager.GetOrganizationsById(studentEntryVm.OrganizationId);
        var course = studentManager.GetCoursesById(studentEntryVm.CourseId);
        student.Organizations = organization.ToList();
        student.Courses = course.ToList();

        bool isSaved = studentManager.SaveStudent(student);
        if (isSaved)
        {
            return View(studentEntryVm);
        }
           

            return View(studentEntryVm);
        }

    public byte[] ConvertToBytes(HttpPostedFileBase image)
    {

        byte[] imageBytes = null;

        BinaryReader reader = new BinaryReader(image.InputStream);

        imageBytes = reader.ReadBytes((int)image.ContentLength);

        return imageBytes;

    }
         public List<SelectListItem> GetOrganizationListItem()
        {
            var organizationList = studentManager.GetOrganization();
            List<SelectListItem> organizationStItems = new List<SelectListItem>();
            foreach (var organization in organizationList)
            {
                var osli = new SelectListItem();
                osli.Text = organization.Name;
                osli.Value = organization.Id.ToString();
                organizationStItems.Add(osli);
            }
            return organizationStItems;
        }
        public List<SelectListItem> GetCourseListItem()
        {
            var courseList = studentManager.GetCourses();
            List<SelectListItem> courseStItems = new List<SelectListItem>();
            foreach (var courses in courseList)
            {
                var osli = new SelectListItem();
                osli.Text = courses.CourseName;
                osli.Value = courses.Id.ToString();
                courseStItems.Add(osli);
            }
            return courseStItems;
        }

        public JsonResult GetLastRegNo()
        {
            var data = studentManager.GetStudent();
            var regNo = 0;
            if (data.Count != 0)
            {
                 regNo = studentManager.GetRegNo();
                
            }

            return Json(regNo, JsonRequestBehavior.AllowGet);
            
        }

    }
}

OnlineExaminationSystem_Mvc/Controllers/TrainerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using BLL;
using Models;
using OnlineExaminationSystem_Mvc.ViewModels.Student;
using OnlineExaminationSystem_Mvc.ViewModels.Trainer;

namespace OnlineExaminationSystem_Mvc.Controllers
{
    public class TrainerController : Controller
    {
        // GET: Trainer
        TrainerManager trainerManager = new TrainerManager();

        // GET: Student
        public ActionResult TrainerEntry()
        {
            TrainerEntryVm trainerEntryVm = new TrainerEntryVm();
            trainerEntryVm.OrganizationSelectListItems = GetOrganizationListItem();
            trainerEntryVm.CourseSelectListItems = GetCourseListItem();

            return View(trainerEntryVm);
        }

        [HttpPost]
        public ActionResult TrainerEntry(TrainerEntryVm trainerEntryVm)
        {
            trainerEntryVm.OrganizationSelectListItems = GetOrganizationListItem();
            trainerEntryVm.CourseSelectListItems = GetCourseListItem();
            var trainer = Mapper.Map<Trainer>(trainerEntryVm);
            var organization = trainerManager.GetOrganizationsById(trainerEntryVm.OrganizationId);
            var course = trainerManager.GetCoursesById(trainerEntryVm.CourseId);
            trainer.Organizations = organization.ToList();
            trainer.Courses = course.ToList();

            bool isSaved = trainerManager.SaveStudent(trainer);
            if (isSaved)
            {
                return View(trainerEntryVm);
            }


            return View(trainerEntryVm);
        }


        public List<SelectListItem> GetOrganizationListItem()
        {
            var organizationList = trainerManager.GetOrganization();
            List<SelectListItem> organizationStItems = new List<SelectListItem>();
            foreach (var organization in organizationList)
            {
                var osli = new SelectListItem();
                osli.Text = organization.Name;
                osli.Value = organization.Id.ToString();
                organizationStItems.Add(osli);
            }
            return organizationStItems;
        }
        public List<SelectListItem> GetCourseListItem()
        {
            var courseList = trainerManager.GetCourses();
            List<SelectListItem> courseStItems = new List<SelectListItem>();
            foreach (var courses in courseList)
            {
                var osli = new SelectListItem();
                osli.Text = courses.CourseName;
                osli.Value = courses.Id.ToString();
                courseStItems.Add(osli);
            }
            return courseStItems;
        }
    }
}

OnlineExaminationSystem_Mvc/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Dashboard">
    <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">

    <title>Exam Management system Admin</title>

    <!-- Bootstrap core CSS -->
    <link href="~/assets/css/bootstrap.css" rel="stylesheet">
    <!--external css-->
    <link href="~/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="~/assets/css/zabuto_calendar.css">
    <link rel="stylesheet" type="text/css" href="~/assets/js/gritter/css/jquery.gritter.css" />
    <link rel="stylesheet" type="text/css" href="~/assets/lineicons/style.css">

    <!-- Custom styles for this template -->
    <link href="~/assets/css/style.css" rel="stylesheet">
    <link href="~/assets/css/style-responsive.css" rel="stylesheet">

    <script src="~/assets/js/chart-master/Chart.js"></script>
    @RenderSection("Content",false)
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

    <section id="container">
        <!-- **********************************************************************************************************************************************************
        TOP BAR CONTENT & NOTIFICATIONS
        *********************************************************************************************************************************************************** -->
        <!--header start-->
        <header class="header black-bg">
            <div class="sidebar-toggle-box">
                <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
            </div>
            <!--logo start-->
            <a href="#" class="logo"><b>Online Examination System</b></a>
            <!--logo end-->

            <div class="top-menu">
                <ul class="nav pull-right top-menu">
                    <li><a class="logout" href="#">Logout</a></li>
                </ul>
            </div>
        </header>
        <!--header end-->
        <!-- **********************************************************************************************************************************************************
        MAIN SIDEBAR MENU
        *********************************************************************************************************************************************************** -->
        <!--sidebar start-->
        <aside>
            <div id="sidebar" class="nav-collapse ">
                <!-- sidebar menu start-->
                <ul class="sidebar-menu" id="nav-accordion">

                    <p class="centered"><a href="#"><img src="~/assets/img/ui-sam.jpg" class="img-circle" width="60"></a></p>
                    <h5 class="centered">Avant Garde</h5>

                    <li class="mt">
                        <a class="active" href="#">
                            <i class="fa fa-dashboard"></i>
                            <span>Dashboard</span>
                        </a>
                    </li>

                    <li class="sub-menu">
                        <a href="javascript:;">
                            <i class="fa fa-building-o"></i>
                            <span>Organization</span>
                        </a>
                        <ul class="sub">
                            <li><a href="@Url.Action("OrganizationEntry", "Organization")" class="elements">Entry</a></li>
                            <li><a href="@Url.Action("OrganizationInformation", "Organization")" class="elements">Information</a></li>
                            <li><a href="@Url.Action("OrganizationSearch", "Organization")" class="elements">Search</a></li>
                        </ul>
                    </li>

                    <li class="sub-menu">
                        <a href="javascript:;">
                            <i class="fa fa-graduation-cap"></i>
                            <span>Course</span>
                        </a>
                        <ul class="sub">
                            <li><a href="@Url.Action("Entry", "Course")" class="elements">Entry</a></li>
                           @*<li><a href="#">Information</a></li>*@
                            <li><a href="@Url.Action("SearchCourse", "Course")" class="elements">Search</a></li>
                        </ul>
                    </li>
                    @*<li class="sub-menu">
                        <a href="javascript:;">
                            <i class="fa fa-users"></i>
                            <span>Batch</span>
                        </a>
                        <ul class="sub">
                            <li><a href="batch-entry.html">Entry</a></li>
                            <li><a href="batch-info.html">Info</a></li>
                            <li><a href="batch-search.html">Search</a></li>
                        </ul>
                    </li>*@
                    <li class="sub-menu">
                        <a href="javascript:;">
                            <i class="fa fa-user"></i>
                            <span>Trainer</span>
                        </a>
                        <ul class="sub">
                            <li><a href="@Url.Action("TrainerEntry", "Trainer")" class="elements">Entry</a></li>
                            @*<li><a href="trainer-info.html">Info</a></li>
                            <li><a href="trainer-search.html">Search</a></li>*@
                        </ul>
                    </li>
                    <li class="sub-menu">
                        <a href="javascript:;">
                            <i class="fa fa-tasks"></i>
                            <span>Exam</span>
                        </a>
                        <ul class="sub">
                            <li><a href="@Url.Action("Entry", "Exam")" class="elements">Entry</a></li>   
                            <li><a href="@Url.Action("ExamAttend", "Exam")" class="elements">Attend Exam</a></li>
                            <li><a href="@Url.Action("ExamResult", "Exam")" class="elements">Result</a></li>
                        </ul>
                    </li>
                    <li class="sub-menu">
                        <a href="javascript:;">
                            <i class="fa fa-users"></i>
                            <span>Students</span>
                        </a>
                        <ul class="sub">
                            <li><a href="@Url.Action("StudentEntry", "Student")" class="elements">Entry</a></li>
                            @*<li><a href="participant-list.html">List</a></li>*@
                        </ul>
                    </li>
                    <li class="sub-menu">
                        <a href="javascript:;">
                            <i class=" fa fa-tasks"></i>
                            <span>Question</span>
                        </a>
                        <ul class="sub">
                            <li><a href="@Url.Action("QuestionAnswerEntry", "Exam")" class="elements">Set Question</a></li>
                            <li><a href="@Url.Action("QuestionSummary", "Exam")" class="elements">Question Summary</a></li>
                        </ul>
                    </li>

                </ul>
                <!-- sidebar menu end-->
            </div>
        </aside>
        <!--sidebar end-->
        <!-- **********************************************************************************************************************************************************
        MAIN CONTENT
        *********************************************************************************************************************************************************** -->
        <!--main content start-->
        <section id="main-content">
            <section class="wrapper">
                @RenderBody()
            </section>
        </section>

        <!--main content end-->
        <!--footer start-->
        <footer class="site-footer">
            <div class="text-center">
                2018-Avant-Garde
                <a href="index.html#" class="go-top">
                    <i class="fa fa-angle-up"></i>
                </a>
            </div>
        </footer>
        <!--footer end-->
    </section>

    <!-- js placed at the end of the document so the pages load faster -->
    <script src="~/assets/js/jquery.js"></script>
    <script src="~/assets/js/jquery-1.8.3.min.js"></script>
    <script src="~/assets/js/bootstrap.min.js"></script>
    <script class="include" type="text/javascript" src="~/assets/js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="~/assets/js/jquery.scrollTo.min.js"></script>
    <script src="~/assets/js/jquery.nicescroll.js" type="text/javascript"></script>
    <script src="~/assets/js/jquery.sparkline.js"></script>


    <!--common script for all pages-->
    <script src="~/assets/js/common-scripts.js"></script>

    <script type="text/javascript" src="~/assets/js/gritter/js/jquery.gritter.js"></script>
    <script type="text/javascript" src="~/assets/js/gritter-conf.js"></script>

    <!--script for this page-->
    <script src="~/assets/js/sparkline-chart.js"></script>
    <script src="~/assets/js/zabuto_calendar.js"></script>



    <script type="application/javascript">
        $(document).ready(function () {
            $("#date-popover").popover({html: true, trigger: "manual"});
            $("#date-popover").hide();
            $("#date-popover").click(function (e) {
                $(this).hide();
            });

            $("#my-calendar").zabuto_calendar({
                action: function () {
                    return myDateFunction(this.id, false);
                },
                action_nav: function () {
                    return myNavFunction(this.id);
                },
                ajax: {
                    url: "show_data.php?action=1",
                    modal: true
                },
                legend: [
                    {type: "text", label: "Special event", badge: "00"},
                    {type: "block", label: "Regular event", }
                ]
            });
        });


        function myNavFunction(id) {
            $("#date-popover").hide();
            var nav = $("#" + id).data("navigation");
            var to = $("#" + id).data("to");
            console.log('nav ' + nav + ' to: ' + to.month + '/' + to.year);
        }
    </script>
    @RenderSection("scripts",false)

</body>
</html>